language: cpp
dist: trusty
sudo: true

cache: ccache

matrix:
  fast_finish: true
  include:

    - env: PLATFORM=Unix COMPILER=gcc
      compiler: gcc
      os: linux

before_install: ./ci/travis-before-install.sh

script: ./ci/travis-script.sh

after_success: ./ci/travis-after-success.sh
